server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: micro1
          uri: https://demo-openshift-git-marcoqrsof-dev.apps.sandbox-m3.1530.p1.openshiftapps.com
          predicates:
            - Path=/micro1/**

